include:
  - local: '/.gitlab-ci.d/container-template.yml'

amd64-centos8-container:
  extends: .container_job_template
  variables:
    QEMU_JOB_MINIMAL: 1
    NAME: centos8

amd64-fedora-container:
  extends: .container_job_template
  variables:
    QEMU_JOB_MINIMAL: 1
    NAME: fedora

amd64-debian10-container:
  extends: .container_job_template
  variables:
    QEMU_JOB_MINIMAL: 1
    QEMU_JOB_PUBLISH: 1
    NAME: debian10
